from django.urls import path

from .views import (
    AdminAppointmentListView,
    AdminAppointmentDetailView,
    AdminDoctorAssignStaffView,
    AdminDoctorListCreateView,
    AdminDoctorDetailView,
    AdminPatientListView,
    AdminScheduleDetailView,
    AdminScheduleListCreateView,
    AdminStaffListCreateView,
    AdminStaffDetailView,
    ApproveCancellationView,
    CurrentUserView,
    DashboardView,
    DoctorAppointmentListView,
    DoctorScheduleDetailView,
    DoctorScheduleListCreateView,
    LoginView,
    MarkAllNotificationsReadView,
    MarkAppointmentDoneView,
    MarkNotificationReadView,
    NotificationListView,
    PatientAppointmentListView,
    PatientBookAppointmentView,
    PatientCancelRequestView,
    PatientDoctorListView,
    PatientDoctorScheduleView,
    PatientSignupView,
    SignupVerificationRequestView,
    DoctorReviewLabResultView,
    PatientSubmitLabResultView,
    PatientSpecializationListView,
    RejectCancellationView,
    SpecializationListCreateView,
    StaffAppointmentListView,
    StaffConfirmAppointmentView,
    StaffDoctorScheduleView,
    StaffRequireLaboratoryView,
)


urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/signup/request-code/", SignupVerificationRequestView.as_view(), name="signup-request-code"),
    path("auth/signup/", PatientSignupView.as_view(), name="patient-signup"),
    path("auth/me/", CurrentUserView.as_view(), name="current-user"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", MarkNotificationReadView.as_view(), name="notification-read"),
    path("notifications/read-all/", MarkAllNotificationsReadView.as_view(), name="notifications-read-all"),
    # Patient
    path("patient/specializations/", PatientSpecializationListView.as_view(), name="patient-specializations"),
    path("patient/doctors/", PatientDoctorListView.as_view(), name="patient-doctors"),
    path("patient/doctors/<int:doctor_id>/schedules/", PatientDoctorScheduleView.as_view(), name="patient-doctor-schedules"),
    path("patient/book/", PatientBookAppointmentView.as_view(), name="patient-book"),
    path("patient/appointments/", PatientAppointmentListView.as_view(), name="patient-appointments"),
    path("patient/appointments/<int:pk>/cancel-request/", PatientCancelRequestView.as_view(), name="patient-cancel-request"),
    path("patient/appointments/<int:pk>/submit-lab-result/", PatientSubmitLabResultView.as_view(), name="patient-submit-lab-result"),
    path("doctor/appointments/<int:pk>/review-lab-result/", DoctorReviewLabResultView.as_view(), name="doctor-review-lab-result"),
    # Approve cancellation (doctor, staff, admin)
    path("appointments/<int:pk>/approve-cancellation/", ApproveCancellationView.as_view(), name="approve-cancellation"),
    path("appointments/<int:pk>/reject-cancellation/", RejectCancellationView.as_view(), name="reject-cancellation"),
    # Admin
    path("admin/specializations/", SpecializationListCreateView.as_view(), name="admin-specializations"),
    path("admin/doctors/", AdminDoctorListCreateView.as_view(), name="admin-doctors"),
    path("admin/doctors/<int:pk>/", AdminDoctorDetailView.as_view(), name="admin-doctor-detail"),
    path("admin/doctors/<int:pk>/assign-staff/", AdminDoctorAssignStaffView.as_view(), name="admin-doctor-assign-staff"),
    path("admin/staff/", AdminStaffListCreateView.as_view(), name="admin-staff"),
    path("admin/staff/<int:pk>/", AdminStaffDetailView.as_view(), name="admin-staff-detail"),
    path("admin/patients/", AdminPatientListView.as_view(), name="admin-patients"),
    path("admin/schedules/", AdminScheduleListCreateView.as_view(), name="admin-schedules"),
    path("admin/schedules/<int:pk>/", AdminScheduleDetailView.as_view(), name="admin-schedule-detail"),
    path("admin/appointments/", AdminAppointmentListView.as_view(), name="admin-appointments"),
    path("admin/appointments/<int:pk>/", AdminAppointmentDetailView.as_view(), name="admin-appointment-detail"),
    # Doctor
    path("doctor/schedules/", DoctorScheduleListCreateView.as_view(), name="doctor-schedules"),
    path("doctor/schedules/<int:pk>/", DoctorScheduleDetailView.as_view(), name="doctor-schedule-detail"),
    path("doctor/appointments/", DoctorAppointmentListView.as_view(), name="doctor-appointments"),
    path("doctor/appointments/<int:pk>/done/", MarkAppointmentDoneView.as_view(), name="doctor-appointment-done"),
    # Staff
    path("staff/doctor-schedules/", StaffDoctorScheduleView.as_view(), name="staff-doctor-schedules"),
    path("staff/appointments/", StaffAppointmentListView.as_view(), name="staff-appointments"),
    path("staff/appointments/<int:pk>/confirm/", StaffConfirmAppointmentView.as_view(), name="staff-confirm-appointment"),
    path("staff/appointments/<int:pk>/require-laboratory/", StaffRequireLaboratoryView.as_view(), name="staff-require-laboratory"),
]
